version: '3.8'

services:
  flutter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
